name: "Release"
on:
  repository_dispatch:
    types: [release]
  workflow_dispatch:
  
  
jobs:
  release:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Tag
       id: autotagger
       uses: anothrNick/github-tag-action@1.38.0
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         WITH_V: false
         RELEASE_BRANCHES: master
         DEFAULT_BUMP: patch
